// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "github.com/baigel/lms/main-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// ChapterRepository is an autogenerated mock type for the ChapterRepository type
type ChapterRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: chapter
func (_m *ChapterRepository) Create(chapter *model.Chapter) error {
	ret := _m.Called(chapter)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Chapter) error); ok {
		r0 = rf(chapter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *ChapterRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllByCourseID provides a mock function with given fields: courseID
func (_m *ChapterRepository) GetAllByCourseID(courseID uint) ([]model.Chapter, error) {
	ret := _m.Called(courseID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByCourseID")
	}

	var r0 []model.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]model.Chapter, error)); ok {
		return rf(courseID)
	}
	if rf, ok := ret.Get(0).(func(uint) []model.Chapter); ok {
		r0 = rf(courseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Chapter)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(courseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *ChapterRepository) GetByID(id uint) (*model.Chapter, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Chapter
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*model.Chapter, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *model.Chapter); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Chapter)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: chapter
func (_m *ChapterRepository) Update(chapter *model.Chapter) error {
	ret := _m.Called(chapter)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Chapter) error); ok {
		r0 = rf(chapter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewChapterRepository creates a new instance of ChapterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChapterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChapterRepository {
	mock := &ChapterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
