// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "github.com/baigel/lms/main-service/internal/model"
	"github.com/baigel/lms/main-service/pkg/pagination"
	mock "github.com/stretchr/testify/mock"
)

// CourseRepository is an autogenerated mock type for the CourseRepository type
type CourseRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: course
func (_m *CourseRepository) Create(course *model.Course) error {
	ret := _m.Called(course)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Course) error); ok {
		r0 = rf(course)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *CourseRepository) Delete(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: p
func (_m *CourseRepository) GetAll(p pagination.Params) ([]model.Course, int64, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Course
	var r1 int64
	var r2 error

	if rf, ok := ret.Get(0).(func(pagination.Params) ([]model.Course, int64, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func(pagination.Params) []model.Course); ok {
		r0 = rf(p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(pagination.Params) int64); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(pagination.Params) error); ok {
		r2 = rf(p)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: id
func (_m *CourseRepository) GetByID(id uint) (*model.Course, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Course
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*model.Course, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *model.Course); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Course)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, updates
func (_m *CourseRepository) Update(id uint, updates map[string]any) error {
	ret := _m.Called(id, updates)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, map[string]any) error); ok {
		r0 = rf(id, updates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCourseRepository creates a new instance of CourseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourseRepository {
	mock := &CourseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
